<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quiz_info[
	<!ELEMENT quiz_info (quiz*)>
	<!ELEMENT quiz (question,choice,answer)>
	<!ELEMENT choice (c+)>
	<!ELEMENT question (#PCDATA)>
	<!ELEMENT answer (#PCDATA)>
	<!ELEMENT c (#PCDATA)>
]>

<quiz_info>
	<quiz>
	    <question>
		    2+2 = ?
	    </question>
		<choice>
			<c>4</c>
			<c>5</c>
			<c>Man Not Hot</c>
			<c>3</c>
		</choice>

		<answer>4</answer>

	</quiz>

<quiz>
<question>
	2+2 = ?
</question>
<choice>
	<c>4</c>
	<c>5</c>
	<c>Man Not Hot</c>
	<c>3</c>
</choice>

<answer>Man Not Hot</answer>

</quiz>
<quiz>
<question>
	2+2 = ?
</question>
<choice>
	<c>4</c>
	<c>5</c>
	<c>Man Not Hot</c>
	<c>3</c>
</choice>

<answer>4</answer>

</quiz>
</quiz_info>